FROM python:3.10-slim

WORKDIR /app

# 1. Copiar e instalar el requirements.txt que está en el directorio actual
COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# 2. Copiar las carpetas del proyecto a /app
COPY api/ /app/api/
COPY modelo/ /app/modelo/

# 3. Iniciar Uvicorn apuntando al archivo api.py dentro de la carpeta api/
CMD ["sh", "-c", "uvicorn api.api:app --host 0.0.0.0 --port ${PORT:-8000}"]